[battery]
full_symbol = "ğŸ™Œ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
unknown_symbol = "ğŸ–ï¸   "

[[battery.display]]
threshold = 100
style = "green"
[[battery.display]]
threshold = 40
style = "yellow"

[[battery.display]]
threshold = 10
style = "red"
